/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.Parking;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import javax.swing.JLabel;

/**
 *
 * @author rubco
 */
public class ParkingPanel extends javax.swing.JPanel {

    /**
     * Creates new form parkingPanel
     */
    public ParkingPanel() {
        initComponents();

        repaint();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        setPreferredSize(new Dimension(1000, 700));

        Graphics2D g2d = (Graphics2D) g;
        g2d.setRenderingHint(
                RenderingHints.KEY_ANTIALIASING,
                RenderingHints.VALUE_ANTIALIAS_ON
        );
        g2d.setColor(new Color(111, 111, 111));
        g2d.fillRect(0, 0, 1000, 300);
        g2d.fillRect(387, 300, 240, 400);
        g2d.fillRect(0, 550, 1000, 150);
        g2d.setColor(Color.LIGHT_GRAY);
        g2d.fillRect(0, 0, 1000, 15);
        g2d.fillRect(0, 300, 395, 15);
        g2d.fillRect(619, 300, 395, 15);
        g2d.fillRect(395, 300, 15, 265);
        g2d.fillRect(500, 300, 15, 400);
        g2d.fillRect(604, 300, 15, 265);
        g2d.fillRect(0, 550, 395, 15);
        g2d.fillRect(619, 550, 395, 15);
        final int ANCHO_LINEA = 15;
        int x_posicion = 0;

        for (int i = 0; i < 5; i++) {
            int ANCHO_PLAZA;
            if (i % 2 == 0) {
                ANCHO_PLAZA = 157;
            } else {
                ANCHO_PLAZA = 156;
            }

            x_posicion += ANCHO_PLAZA;

            g2d.fillRect(x_posicion, 0, ANCHO_LINEA, 270);
            x_posicion += ANCHO_LINEA;
        }

        g2d.setColor(new Color(101, 161, 100));
        g2d.fillRect(0, 315, 387, 235);
        g2d.fillRect(627, 315, 387, 235);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
